export const NAME = 'cart'

export const CREATE_NEW_CART = 'CREATE_NEW_CART'
export const ADD_CART_ITEM = 'ADD_CART_ITEM'
export const SET_CART_DETAILS = 'SET_CART_DETAILS'
export const SET_CART_USER_INFO = 'SET_CART_USER_INFO'
export const SET_CART_USER_ADDRESS = 'SET_CART_USER_ADDRESS'
export const SET_CART_USER_ADDRESSES = 'SET_CART_USER_ADDRESSES'
