export const NAME = 'order'

export const SET_ORDER_SEARCH_STATUS = 'SET_ORDER_SEARCH_STATUS'
export const SET_ORDERS_INFO = 'SET_ORDERS_INFO'
export const SET_ORDER_TO_DISPLAY = 'SET_ORDER_TO_DISPLAY'
export const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS'
export const SET_IN_PROGRESS_ORDER_DETAILS = 'SET_IN_PROGRESS_ORDER_DETAILS'
export const SET_ORDER_TRANSACTION_DETAILS = 'SET_ORDER_TRANSACTION_DETAILS'
