import React from 'react'
import {Row, Col, Card, Modal, CardBody, Input} from 'reactstrap'
import {makeStyles} from '@material-ui/core/styles'
import PropTypes from 'prop-types'
import CommonDemo from 'routes/components/CommonDemo'
import CommonButton from 'routes/components/CommonButton'

const useStyles = makeStyles({
  modal: {
    '& .card': {
      boxShadow: 'none',
    },
    '& .sub-title': {
      fontFamily: 'DINCondensed-Bold',
      fontSize: '22px',
      fontWeight: 'bold',
      color: '#403839',
    },
    '& .label': {
      fontFamily: 'SFUIText-Bold',
      fontSize: '12px',
      fontWeight: 'bold',
      color: '#403839',
    },
  },
})

const CodeFormatModal = ({modal, toggle}) => {
  const classes = useStyles()

  return (
    <Modal isOpen={modal} toggle={toggle} className={`${classes.modal}  mx-4 mx-sm-auto`}>
      <Card>
        <CardBody>
          <span className="sub-title">Set Default Code Format</span>
          <hr />

          <CommonDemo
            item="danger"
            wrapperClass="mx-0"
            content="Set the default format for codes that are generated from gift card products
             being purchased on orders. The codes will be autogenerated based on the format that
              you specify. You can enter the uppercase A for an alphabetic character, a hashtag
               for a number between 0 and 9, or a dash (-)."
            contentOne="Feature Guide Link "
            contentTwo={<i className="fa fas fa-long-arrow-right"></i>}
          />
          <Row className="mb-3">
            <Col md={5}>Default Code Format</Col>
            <Col className="pl-3 pl-md-0">
              <Input placeholder="AA##-AA##" className="mb-2" />
              <span>Example code: CK24-LF43</span>
            </Col>
          </Row>
          <Row>
            <Col className="mb-2">
              <CommonButton
                title="Cancel"
                buttonType="cancelButton"
                onClick={toggle}
                wrapperClass="ml-0"
                width={150}
                height={40}
              />
            </Col>
            <Col sm="auto">
              <CommonButton
                title="Save"
                buttonType="addButton"
                wrapperClass="ml-0"
                width={150}
                height={40}
              />
            </Col>
          </Row>
        </CardBody>
      </Card>
    </Modal>
  )
}

CodeFormatModal.propTypes = {
  modal: PropTypes.bool,
  toggle: PropTypes.func,
}

export default CodeFormatModal
