export const NAME = 'products'

export const SET_ALL_PRODUCTS = 'SET_ALL_PRODUCTS'
export const SET_PRODUCT_TO_DISPLAY = 'SET_PRODUCT_TO_DISPLAY'
export const SET_PRODUCT_DETAILS = 'SET_PRODUCT_DETAILS'