export const fieldGroupFields = [
  {
    label: 'Communication',
    fields: ['Broadcast Message Info', 'Consultant Upline Autoresponder'],
  },
  {
    label: 'Consultant Center',
    fields: [
      'Consultant Contact Info',
      'Consultant Legal Docs',
      'Consultant Other Info',
      'Consultant Party',
      'Consultant Payment Info',
      'Consultant Sensitive Info',
      'Consultant Shipping Info',
    ],
  },
  {
    label: 'Customer Center',
    fields: [
      'Customer Contact Info',
      'Customer Other Info',
      'Customer Party',
      'Customer Payment Info',
      'Customer Sensitive Info',
      'Customer Shipping Info',
    ],
  },
  {
    label: 'Lead Center',
    fields: ['Lead Contact Info', 'Lead Other Info', 'Lead Shipping Info'],
  },
  {
    label: 'Order Center',
    fields: ['Order General Info'],
  },
  {
    label: 'Processing',
    fields: ['Compensation Process'],
  },
  {
    label: 'Product Center',
    fields: ['Product Display Info', 'Product General Info'],
  },
  {
    label: 'Purchase Order Center',
    fields: ['Purchase Order'],
  },
  {
    label: 'Shiping Center',
    fields: ['Shipping General Info'],
  },
  {
    label: 'System Generated',
    fields: ['System Generated'],
  },
  {
    label: 'Vendor Center',
    fields: [
      'Vendor Bill From Address',
      'Vendor Contact Info',
      'Vendor Other Info',
      'Vendor Sensitive Info',
      'Vendor Shipping Info',
    ],
  },
  {
    label: 'Warehouse Center',
    fields: ['Warehouse Associations', 'Warehouse General Info', 'Warehouse Shipping Info'],
  },
]

export const moduleFields = [
  {label: 'Communications', fields: ['Autoresponders', 'Broadcast Messages', 'Email Templates']},
  {
    label: 'Company',
    fields: [
      'Client Support',
      'Create Gateway Info',
      'Custom Field Management',
      'Edit Existing Address Validation Integration',
      'Edit Existing Tax Integration',
      'Edit Gateway Info',
      'Field Management',
      'IP Management',
      'Lead Capture Form Management',
      'Legal Agreement Management',
      'Media Manager',
      'Menu Item Management',
      'Send Email Test',
      'Settings Management',
      'Sky Wallet Manager',
      'Time Management',
      'Translation Management',
      'User Activity',
      'User Login Security Settings',
      'User Management',
      'View Existing Tax Integration',
      'View Gateway Info',
    ],
  },
  {
    label: 'Compensation',
    fields: [
      'Compensation Payout Method Management',
      'Compensation Run Management',
      'Generate Compensation Plan Document',
      'Sky Wallet Payouts',
      'View Compensation',
    ],
  },
  {
    label: 'Consultant',
    fields: [
      'Add Adjustment',
      'Adjust Sky Wallet',
      'Cancel Consultant',
      'Cancel Subscription',
      'Change Genealogy',
      'Consultant Bulk Information',
      'Consultant Center',
      'Consultant Create Customer',
      'Consultant Create Lead',
      'Consultant Create Order',
      'Consultant Financials',
      'Consultant Reports',
      'Create Consultant',
      'Create Customer From Consultant',
      'Create Note',
      'Create Payment',
      'Create Shipping Address',
      'Delete Adjustment',
      'Delete Note',
      'Delete Payment',
      'Delete Shipping Address',
      'Edit Accounts',
      'Edit Adjustment',
      'Edit Consultant',
      'Edit Custom Fields',
      'Edit Metric Overrides',
      'Edit Note',
      'Edit Payment',
      'Edit Qualification Overrides',
      'Edit Shipping Address',
      'Edit Subscription',
      'Join Option Management',
      'Login Consultant Portal',
      'Manage Subscriptions',
      'Reactivate Consultant',
      'View Adjustments',
      'View Customers',
      'View Downline',
      'View Earnings',
      'View Events',
      'View Graphical Downline',
      'View Leads',
      'View Metric Overrides',
      'View Notes',
      'View Orders',
      'View Payment Methods',
      'View Personally Sponsored',
      'View Qualification Overrides',
      'View Shipping Addresses',
      'View Sky Wallet',
    ],
  },
  {
    label: 'Consultant Restricted Rep URL Words',
    fields: ['Manage Consultant Restricted Rep URL Words'],
  },
  {
    label: 'Countries',
    fields: ['Country Management', 'Manage Disabled Countries'],
  },
  {
    label: 'Customer',
    fields: [
      'Adjust Sky Wallet',
      'Cancel Subscription',
      'Change Genealogy',
      'Create Customer From Consultant',
      'Create Customer',
      'Create Note',
      'Create Payment',
      'Create Shipping Address',
      'Customer Center',
      'Customer Reports',
      'Delete Note',
      'Delete Payment',
      'Delete Shipping Address',
      'Edit Accounts',
      'Edit Customer',
      'Edit Custom Fields',
      'Edit Note',
      'Edit Payment',
      'Edit Shipping Address',
      'Edit Subscription',
      'Login Customer Portal',
      'Manage Subscriptions',
      'Reactivate Customer',
      'View Events',
      'View Leads',
      'View Notes',
      'View Orders',
      'View Payment Methods',
      'View Shipping Addresses',
      'View Sky Wallet',
    ],
  },
  {
    label: 'Events',
    fields: ['Manage Events', 'Manage Party Types'],
  },
  {
    label: 'Export Data',
    fields: ['Export Data'],
  },
  {
    label: 'General System Access - Flight',
    fields: [
      'Acuta Required',
      'Home Page',
      'Home Page - Dashboard Reports',
      'Reference Data',
      'Shopping',
      'Validators',
    ],
  },
  {
    label: 'Import Data',
    fields: ['Import Data'],
  },
  {
    label: 'Knowledge Center',
    fields: ['Help Text', 'Knowledge Base', 'Knowledge Base Admin'],
  },
  {
    label: 'Lead',
    fields: [
      'Change Genealogy',
      'Change Referer',
      'Create Lead',
      'Create Note',
      'Create Shipping Address',
      'Delete Note',
      'Delete Shipping Address',
      'Edit Custom Fields',
      'Edit Shipping Address',
      'Lead Center',
      'Manage Lead Types',
      'Promote Lead',
      'View Leads',
      'View Notes',
      'View Shipping Addresses',
    ],
  },
  {
    label: 'Orders',
    fields: [
      'Add Order Line',
      'Back Orders',
      'Change Order Commission Date',
      'Change Order Commission Owner',
      'Change Order Ship Hold Status',
      'Copy Order',
      'Create Note',
      'Create Order',
      'Create Return Request',
      'Delete Note',
      'Delete Order Line',
      'Edit Custom Fields',
      'Edit Note',
      'Edit Order Line',
      'Edit Shipping Address',
      'Edit Shipping Method',
      'Financials',
      'Lock Order',
      'Mark Commissionable',
      'Mark Non-Commissionable',
      'Order Center',
      'Order History',
      'Order Payments',
      'Post Order',
      'Process Return',
      'Recalculate Order',
      'Reduce Volume on Refund',
      'Refund Payment',
      'Ship Order',
      'Shipments',
      'View Invoice',
      'View Notes',
      'Void Order',
    ],
  },
  {
    label: 'Portal Configuration',
    fields: [
      'Announcement Manager',
      'Banner Manager',
      'Consultant Repl Site Settings',
      'Edit Portal Resources',
      'Menu Item Manager',
      'View Portal Resources',
    ],
  },
  {label: 'Processing', fields: ['Manage Scheduled Process Queue']},
  {
    label: 'Products',
    fields: [
      'Add Variation',
      'Assign/Unassign Warehouse Bin',
      'Create Product',
      'Discount Rule Manager',
      'Edit Association Items',
      'Edit Availability',
      'Edit Custom Fields',
      'Edit Kit',
      'Edit Pricing',
      'Edit Product',
      'Edit Product Vendors',
      'Edit Variation',
      'Edit Variation Type Order',
      'Edit Warehouse Level',
      'Manage Display Settings',
      'Manage Gift Cards',
      'Manage Product Classifications',
      'Manage Product Display Categories',
      'Manage Product Tax Codes',
      'Manage Product Types',
      'Manage Product Variation Types',
      'Price Rule Manager',
      'Price Simulator',
      'Product Center',
      'View Product Vendors',
    ],
  },
  {
    label: 'Reporting',
    fields: [
      'Add New Report',
      'Edit Report',
      'Get Invoice Reports',
      'List Reports',
      'Manage Reports',
      'View Report',
    ],
  },
  {
    label: 'Rewards Center',
    fields: [
      'Create/Edit Coupon Types',
      'Create/Edit Host Rewards',
      'Create/Edit Promotional Rewards',
      'Rewards Manager',
    ],
  },
  {label: 'Security', fields: ['Create External Login', 'View API Permissions']},
  {label: 'Sensitive Data', fields: ['Tax IDs']},
  {
    label: 'Shipping',
    fields: [
      'Adjustment Type Manager',
      'Create Shipping File Run',
      'Create/Edit/Delete Shipping File Export Configuration',
      'Create/Edit/Delete Shipping File Import Configuration',
      'Edit Warehouse',
      'Edit Warehouse Levels',
      'Export Shipping File',
      'Import Shipping File',
      'Manage Refund Options',
      'Manage Return Instructions',
      'Manage Return Reasons',
      'Shipping Center',
      'Shipping File Import Center',
      'Shipping/Handling Charge Management',
      'Warehouse Center',
    ],
  },
  {
    label: 'Subscriptions',
    fields: ['Subscription Configuration Management', 'Subscription Run Management'],
  },
  {
    label: 'Trigger Options',
    fields: ['Create/Edit Trigger Options', 'Trigger Options Manager'],
  },
  {
    label: 'Vendor',
    fields: [
      'Add Vendor Products',
      'Create Note',
      'Create Shipping Address',
      'Create Vendor',
      'Create/Edit Purchase Orders',
      'Delete Note',
      'Delete Shipping Address',
      'Edit Custom Fields',
      'Edit Note',
      'Edit Shipping Address',
      'Edit Vendor',
      'Edit Vendor Products',
      'Manage Vendor Type',
      'Purchase Order Center',
      'Vendor Center',
      'View Notes',
      'View Purchase Orders',
      'View Shipping Addresses',
      'View Vendor Products',
    ],
  },
]
