export const consultantOptions = [
  {label: 'Username', value: 'username'},
  {label: 'Email', value: 'email'},
  {label: 'First Name', value: 'first_name'},
  {label: 'Last Name', value: 'last_name'},
  {label: 'Company Name', value: 'company_name'},
  {label: 'Website Url', value: 'website_url'},
  {label: 'Phone', value: 'phone'},
  {label: 'Date of Birth', value: 'date_of_birth'},
  {label: 'SSN', value: 'ssn'},
  {label: 'Address Company Name', value: 'billing_address.company_name'},
  {label: 'Address City', value: 'billing_address.city'},
  {label: 'Address Country', value: 'billing_address.country'},
  {label: 'Address First Name', value: 'billing_address.first_name'},
  {label: 'Address Last Name', value: 'billing_address.last_name'},
  {label: 'Address Phone Number', value: 'billing_address.phone_number'},
  {label: 'Address Postal Code', value: 'billing_address.postcode'},
  {label: 'Address Province', value: 'billing_address.county'},
  {label: 'Address Street 1', value: 'billing_address.line_1'},
  {label: 'Address Street 2', value: 'billing_address.line_2'},
]
