const data = [
  {
    id: 1,
    time_date: '8/27/2017 7:11 AM - 8/31/2017 1:53 AM',
    name: '1/2 Case Club Discount',
    description: 'Volume Discount',
    product_classifications:'10 % Scout & Cellar Birthday Discount',
    price_adjustment: 'Subtract 5.00 %',
    price_classifications: 'Consultant, Executive Consultant, Retail, Senior Consultant',
    country: 'All',
    quantity_range: '1 - 99999',
  },
  {
    id: 2,
    time_date: '8/27/2017 7:09 AM - 8/31/2017 1:53 AM',
    name: 'Case Club Membership Discount',
    description: 'Volume Discount',
    product_classifications:'10 % Scout & Cellar Birthday Discount',
    price_adjustment: 'Subtract 10.00 %',
    price_classifications: 'Consultant, Executive Consultant, Retail, Senior Consultant',
    country: 'All',
    quantity_range: '1 - 99999',
  },
  {
    id: 3,
    time_date: '8/9/2017 7:57 AM - 8/31/2017 1:53 AM',
    name: 'Case Discount',
    description: 'Volume Discount',
    product_classifications:'10 % Scout & Cellar Birthday Discount',
    price_adjustment: 'Subtract 20.00 %',
    price_classifications: 'Retail',
    country: 'All',
    quantity_range: '12 - 99999',
  },
  {
    id: 4,
    time_date: '8/27/2017 7:11 AM - 8/31/2017 1:53 AM',
    name: '1/2 Case Club Discount',
    description: 'Volume Discount',
    product_classifications:'10 % Scout & Cellar Birthday Discount',
    price_adjustment: 'Subtract 5.00 %',
    price_classifications: 'Consultant, Executive Consultant, Retail, Senior Consultant',
    country: 'All',
    quantity_range: '1 - 99999',
  },
  {
    id: 5,
    time_date: '8/27/2017 7:09 AM - 8/31/2017 1:53 AM',
    name: 'Case Club Membership Discount',
    description: 'Volume Discount',
    product_classifications:'10 % Scout & Cellar Birthday Discount',
    price_adjustment: 'Subtract 10.00 %',
    price_classifications: 'Consultant, Executive Consultant, Retail, Senior Consultant',
    country: 'All',
    quantity_range: '1 - 99999',
  },
  {
    id: 6,
    time_date: '8/9/2017 7:57 AM - 8/31/2017 1:53 AM',
    name: 'Case Discount',
    description: 'Volume Discount',
    product_classifications:'10 % Scout & Cellar Birthday Discount',
    price_adjustment: 'Subtract 20.00 %',
    price_classifications: 'Retail',
    country: 'All',
    quantity_range: '12 - 99999',
  },
]

export default data
