import React, {useContext, useEffect} from 'react'
import {Row, Col, Card, CardBody} from 'reactstrap'
import {makeStyles} from '@material-ui/styles'
import {useHistory} from 'react-router-dom'
import GenerateCardForm from './components/GenerateCardForm'
import AppContext from 'components/App/AppContext'
import CommonDemo from 'routes/components/CommonDemo'
import CommonButton from 'routes/components/CommonButton'

const useStyles = makeStyles({
  root: {
    '& .title': {
      fontSize: '32px',
      color: '#403839',
      fontFamily: 'DINCondensed-Bold',
    },
    '& .sub-title': {
      fontFamily: 'DINCondensed-Bold',
      fontSize: '22px',
      fontWeight: 'bold',
      color: '#403839',
    },
    '& .pointer': {
      cursor: 'pointer',
    },
  },
})

const CreateGiftCard = () => {
  const classes = useStyles()
  const context = useContext(AppContext)
  const {setTitle} = context

  const history = useHistory()

  useEffect(() => {
    setTitle('Gift Cards > Generate Gift Card')
  }, [])

  const routeChange = () => {
    history.push('/products/gift-card-manager')
  }

  const countryOptions = [
    {
      label: 'United States',
      value: 1,
    },
  ]

  return (
    <div className={`${classes.root} px-3 px-lg-0 mt-3 mt-lg-0`}>
      <span className="title">Generate Gift Card</span>
      <Card className="my-3">
        <CardBody>
          <span className="sub-title">Basic Info</span>
          <hr />
          <CommonDemo
            item="danger"
            wrapperClass="mx-0"
            content="Here you can generate 1 or many new gift card codes in the format, value, 
            and currency that you would like. The codes will be autogenerated based on the format 
            that you specify. You can enter the uppercase A for an alphabetic character, a hashtag 
            for a number between 0 and 9, or a dash (-)."
            contentOne="Feature Guide Link "
            contentTwo={<i className="fa fas fa-long-arrow-right"></i>}
          />
          <GenerateCardForm />
        </CardBody>
      </Card>
      <Row className="my-4">
        <Col className="d-flex justify-content-lg-end mb-2">
          <CommonButton
            title="Cancel"
            buttonType="cancelButton"
            onClick={routeChange}
            wrapperClass="ml-0"
          />
        </Col>
        <Col sm="auto" className="d-flex justify-content-lg-end">
          <CommonButton title="Generate Code" buttonType="addItemButton" wrapperClass="ml-0" />
        </Col>
      </Row>
    </div>
  )
}

export default CreateGiftCard
